### ISSUE TITLE
Global and project variables in R.

### ISSUE THREAD

**Issue by gavg712** [north-road/qgis-processing-r#100]
This is my official request about global and project variables as objects available in R. I am not sure how important it would be to have these variables. But here are some ideas I have been working on.

Taking a bit from #37 and #31 and my own needs, I have thought that a new parser could be generated for a header line that would allow to have the QGIS variables we need. Use cases:

- Change the working directory to the project path.
- Customize graph and log outputs using global or project variables.
- Save intermediate results as resources or backups for other projects.

My progress allows me to have most variables available, except for the project variables `"layers"` and `"_project_transform_context"` 

Here an example:
![image](https://user-images.githubusercontent.com/8514904/139324268-3a55d462-689e-4d53-a090-6cb6312f707a.png)

And the R session behavior 
![image](https://user-images.githubusercontent.com/8514904/139324750-05b95a92-0d93-4e01-b4ee-7a0a47f8084c.png)

@nyalldawson, @JanCaha, Guys, I think you have already seen this on twitter. But I wanted to ask you directly, do you think it is a good idea to include it in the plugin?

**Comment by JanCaha** [comment]
The first try is available in my fork. Seems to be working rather fine. I need to find some time to write unit tests to be sure ;-)

If you want to take a look, [this commit](https://github.com/JanCaha/qgis-processing-r/commit/6327db371169d19f954c335b7bad2dd712d23ce4) handles most of the important stuff.

**Comment by nyalldawson** [comment]
@JanCaha does that expose them as expression ** inputs ** to the user though? (I don't think we want that, right?)

**Comment by JanCaha** [comment]
It does expose them. To be honest I did not really think about that...I was focused on the functionality. You are right that it is probably not desirable.

**Comment by gavg712** [comment]
It seems to be solved in #102. Then I will close it!
