### ISSUE TITLE
ImportError: cannot import name 'QgsProcessingParameterColor'

### ISSUE THREAD

**Issue by tohka** [north-road/qgis-processing-r#105]
There was a report in the Japanese forum that an error occurred when running in QGIS 3.8.

Processing R Provider version 3.1.0 states that it supports QGIS 3.4 or higher, but QGIS 3.4 does not yet have QgsProcessingParameterColor.

**Comment by JanCaha** [comment]
We should probably raise the supported version to 3.16 or something like that. Both 3.4 and 3.8 are really old.

**Comment by nyalldawson** [comment]
> Both 3.4 and 3.8 are really old.

True, but in this case it's trivial to fix support for these versions (just need to gracefully catch an ImportError). I lean toward only dropping support for older reasons when there's a significantly justifiable reason for doing this
