### ISSUE TITLE
R packages `rgdal` and others will be retired

### ISSUE THREAD

**Issue by gavg712** [north-road/qgis-processing-r#109]
Hi friends,

To keep in mind. The R packages `rgdal`, `rgeos` and `maptools` will be retired at the end of 2023 ([info](https://r-spatial.org/r/2022/04/12/evolution.html)) . Then, you should consider removing from the list of required packages for the plugin and any instructions for automatic installation of `rgdal` on first run. Also, some parameters like `load_<some>_using_rgdal` will be deprecated.

There should also (maybe this is not the place to comment it) be considered a strategy to handle the migrated QGIS 2.x scripts that are currently shared via QGIS Resources Sharing.

Cheers, 
Gabo Gaona

**Comment by JanCaha** [comment]
Solved by removing `rdal` functions and raising an error if code for using is found in the script.
