### ISSUE TITLE
problem with input table

### ISSUE THREAD

**Issue by ofri-sh** [north-road/qgis-processing-r#110]
Hi, 

The option to read tables doesn't working for me. 
I tried "##layer=table" but I get this message: 

![image](https://user-images.githubusercontent.com/80089133/166209200-e8607e25-70a3-4e86-864e-0e11233ba1fe.png)

Thanks, ofri

**Comment by JanCaha** [comment]
I believe that you need to specify the input to be vector (it will be be read without geometry) into R. The explicit specification of table only works for outputs from the scripts...
