### ISSUE TITLE
Testing boolean syntax

### ISSUE THREAD

**Issue by ghtmtt** [north-road/qgis-processing-r#12]
Small issue but achievable in another way.

One custom R syntax way to test if a variable is `TRUE` or `FALSE` is:

```R
v = FALSE

if(!v){
  print('false false')
}
```

in QGIS 2.x this worked while now not and it gives an error:

```
Error in !Regression : invalid argument type
Execution halted
```

This could be easily achieved by changing the syntax to:

```R
v = FALSE

if(v == FALSE){
  print('false false')
}
```

just reporting for compatibility with old scripts. We can change the QGIS docs with the updated syntax to use

**Comment by nyalldawson** [comment]
If I understand correctly - this is entirely an R issue, right? There's nothing in the plugin which needs to change?

**Comment by ghtmtt** [comment]
OK. I think the porting of some scripts could not be 100% (as in the case described above), but I can add a small section *R Script migration* in the docs where we can describe possible issues like this.

There are some R related problems more than plugin ones, so QGIS is not guilty, but users can freak out :)

**Comment by mdsumner** [comment]
I'm happy to review scripts, I'm confident in saying that example above is not a problem in R, it never needed explicit `... == FALSE`, so something else is going on here.

**Comment by nyalldawson** [comment]
Ah - I see the issue. Boolean parameters are incorrectly being set to string literals of false/true.
