### ISSUE TITLE
Possibilities to publish a script tool as a plugin

### ISSUE THREAD

**Issue by wdkang** [north-road/qgis-processing-r#121]
Hello,

I am relatively new to the idea of developing add-ins/plugins. I am wondering if it is possible to package a R script or a group of R scripts  and publish it as a plugin that a user can install without having to worry about the scripts and where to place them?

**Comment by JanCaha** [comment]
It might be possible, but i dont think it is actually easy to set up. You would need two main steps to make it work:
- make sure that the **Processing R** plugin is installed  (i am not 100% sure but i think that there might be field for plugin dependency in metadata.txt) + it needs to be correctly set up (but that is beyond your control)
-  add folder with your scripts to **Processing R** settings of scripts folders (that should be fairly easy)

What I personally do is use [QGIS Resource Sharing](https://qgis-contribution.github.io/QGIS-ResourceSharing/) plugin. With that you can set up github repository and put your Python tools, R scripts and other stuff there and simply add it as resource in the plugin. Feel free to look at my [repo with scripts](https://github.com/JanCaha/qgis-tools-repository) to take a look at the set up.
