### ISSUE TITLE
Possibility to specify the symbology of output rasters

### ISSUE THREAD

**Issue by wdkang** [north-road/qgis-processing-r#122]
Hello,

If the output of the script tool is a raster, is there a way to programmatically change the color ramp when it is loaded into QGIS after execution, so that it is not the default color ramp in grey scale?

Thank you

**Comment by JanCaha** [comment]
Not really, at least directly. You would have to wrap the the algorithm into another tool that would take care of the styling. 

One option could be to create a model, that runs your custom `R Algorithm` and after that runs `Set Layer Style` algorithm which is used to style a layer (vector or raster).
