### ISSUE TITLE
Plugin refactoring

### ISSUE THREAD

**Issue by JanCaha** [north-road/qgis-processing-r#127]
With the latest changes that i did, some issues that could be addressed came up to my mind:

- I would like to run black formatter on the whole code base to make code style consistent. It would be a massive change, but should make the code more readable. Some sections - even my code sections are not that well formatted right now. Code check would be part of CI checks.
- I would like to refactor tests to use pytest - that should make tests more readable a break them into more manageable and readable blocks. 
- With tests refactor, I would like to get rid of some of those default QGIS python tests that I believe are no longer necessary and slightly pollute the test space. 

Any objections to those @nyalldawson?

**Comment by nyalldawson** [comment]
All sounds good to me!

**Comment by JanCaha** [comment]
Ok, cool.

@Gustry I will take a look, sounds like a good idea. Thanks for the suggestion
