### ISSUE TITLE
[Windows SO][Bug?] Detect R folder

### ISSUE THREAD

**Issue by jonnyforestGIS** [north-road/qgis-processing-r#15]
Hi, Nyall
The plugin find the right folder but give the dialog with don't detect.
I have my R folder in the Program Files.

I clean the default profile to have a clean environment and install r-processing plugin but i have the same issue from version 0.0.2

 @PedroVenancio and I are testing the r-processing for Windows.

**Comment by nyalldawson** [comment]
Can you test with current master version? This should output some debug text to the log panel, under the R tab when you attempt to run an algorithm. It will give the current determined path for the R executable.

**Comment by jonnyforestGIS** [comment]
Steps.

1. Erase the default profile.
2. Don't import settings from 2.x
3. Copy and past in the QGIS plugins the r processing plugin master folder.
4. Run QGIS 3.4.1. Activate the R (assume correctly the path of R in processing settings providers) My case: C:\Program Files\R\R-3.2.0
5. Run the test script and give me same behavior (Can't find R).

Don't appear nothing in the python warnings or processing log viewer or processing results.
I'm doing something wrong?

**Comment by PedroVenancio** [comment]
@jonnyforestGIS 
The problem is fixed here, with the release 0.0.3.

**Comment by nyalldawson** [comment]
@jonnyforestGIS

I suspect an installation issue there. Try this version -- it will work using the "install plugin from zip" option from the plugins dialog:

[r.zip](https://github.com/north-road/qgis-processing-r/files/2617772/r.zip)

**Comment by nyalldawson** [comment]
@jonnyforestGIS 

When it's done and you try to run an algorithm, you should see a line like this in the message log panel:

![image](https://user-images.githubusercontent.com/1829991/49049814-51d20000-f22c-11e8-8f82-158d12545f83.png)

**Comment by jonnyforestGIS** [comment]
Ok @nyalldawson. I will try and give you feedback tomorrow.

**Comment by nyalldawson** [comment]
Thanks @jonnyforestGIS -- I'm keen to get this stable, as these binary paths were a persistently annoying issue with the old 2.x version of the provider.

**Comment by jonnyforestGIS** [comment]
Hi :+1:  it's working. @nyalldawson I will close this issue. What are the next steps for this provider? Do you intend to put the same features as qgis 2.x? For example Right click to see and change the code for example?

**Comment by nyalldawson** [comment]
@jonnyforestGIS you should already be able to edit existing scripts via right click.

The current roadmap is basically outlined via the open tickets here. There's a handful of remain parts to implement still.

**Comment by jonnyforestGIS** [comment]
I confirm @nyalldawson . 
I just test a sample code of R Histogram equal to QGIS 2.x and give me an error on QGIS 3.x. I will open a new issue with this subject. 
Feel free to notify me for extra tests in Windows Environment. Good work.
