### ISSUE TITLE
python error during plugin installation win 10

### ISSUE THREAD

**Issue by pigreco** [north-road/qgis-processing-r#17]
I downloaded the zipped file from the repository [0] and tried to install the plugin via installation with zip file, during the installation appears this error:

![image](https://user-images.githubusercontent.com/7631137/51316745-e2230900-1a55-11e9-8c91-de1761fec144.png)

[0] https://github.com/north-road/qgis-processing-r

WIN 10 64b
OSGeo4W QGIS 3.4.3 Madeira

**Comment by jonnyforestGIS** [comment]
@pigreco  for me is working with same background:
WIN 10 64b
OSGeo4W QGIS 3.4.3 Madeira

You need to unzip the of github repo and inside you have folder R that you need to zip to work  via ZIP Install.
Cheers
João

**Comment by pigreco** [comment]
@jonnyforestGIS 
now I can install it, but I still can not make it work:
these are my settings:
![image](https://user-images.githubusercontent.com/7631137/51327997-b6624c00-1a72-11e9-93ed-3b8743622ef6.png)

where am I wrong?

Thanks for your help

**Comment by jonnyforestGIS** [comment]
@pigreco sorry for my delay. Did you found the problem?

**Comment by pigreco** [comment]
@jonnyforestGIS 
after installation I find only an R script,
all the others??

![image](https://user-images.githubusercontent.com/7631137/52040952-51f6c080-2539-11e9-98ad-c35b574811d9.png)

**Comment by nyalldawson** [comment]
@pigreco you need to write them - the included one is just a sample.

**Comment by jonnyforestGIS** [comment]
@pigreco and @nyalldawson I think this issue can be close?

**Comment by pigreco** [comment]
@jonnyforestGIS 
For me yes

**Comment by liaduarte** [comment]
Hello.

I have the same problem. How do you write new ones?

**Comment by jonnyforestGIS** [comment]
@liaduarte  I didn't find as well any button to create a new script file. Do you confirm @nyalldawson?
As a workaround, you can copy the example file .rsx of the folder
**....\QGIS\QGIS3\profiles\default\python\plugins\processing_r\builtin_scripts** and paste in
**.....\QGIS\QGIS3\profiles\default\processing\rscripts**
then disable and enable the R provider. After this you can open with right click the example .rsx and you will have the option of edit script file. After you edit your new script save as a new script .rsx.

Cheers,
João

**Comment by nyalldawson** [comment]
@jonnyforestGIS 

You should see this in the Processing Toolbox toolbar:

![image](https://user-images.githubusercontent.com/1829991/53052524-b5e22880-34ea-11e9-9b30-8e9edc9d1e55.png)

Click the "R" button and you'll get the option to create a new script. (I think it may require a restart to get this button to show the first time after installing the plugin)

**Comment by jonnyforestGIS** [comment]
Yes, @nyalldawson  i confirm. After restart QGIS, the magic button appears. :) @liaduarte please give feedback if this happens to you.

**Comment by liaduarte** [comment]
Yes, I did it too!! :) The button appears.

Thank you very much for your help.
