### ISSUE TITLE
Example plot script not working with integers

### ISSUE THREAD

**Issue by ghtmtt** [north-road/qgis-processing-r#18]
I guess it is related also for other custom plot types. The example `plot` script fails saying:

```
Error in hist.default(FX) : 'x' must be numeric
Calls: hist -> hist -> hist.default
Execution halted
```

if the field chosen is integer, no problem if is real number.

**Comment by nyalldawson** [comment]
Which example script are you referring to?

**Comment by ghtmtt** [comment]
the `plot` one. The layer comes from a geopackage and this is the error:

```
Integer64 fields read as strings: ID ROTAZ DIMENS VALORE
Error in hist.default(FX) : 'x' must be numeric
Calls: hist -> hist -> hist.default
Execution halted
```

**Comment by nyalldawson** [comment]
@ghtmtt I'm tempted to drop that sample script. I think we could find a better example which is easier to understand.

**Comment by ghtmtt** [comment]
What about something easy like:

```
##showplots
##Layer=vector
##X=Field Layer
##Y=Field Layer

# simple scatterplot
plot(Layer[[X]], Layer[[Y]])
```

**Comment by nyalldawson** [comment]
That looks much cleaner!
