### ISSUE TITLE
Buggy editor on creating new scripts

### ISSUE THREAD

**Issue by nyalldawson** [north-road/qgis-processing-r#2]
Script editor has a number of issues, e.g. names new scripts with the ".rsx.py" extension.

Also cannot run scripts directly from the editor.

**Comment by nyalldawson** [comment]
Also needs an option to set the algorithm help -- refs #5

**Comment by jonnyforestGIS** [comment]
I confirm this i put in attach an animated gif.

![scripteditorprocessing](https://user-images.githubusercontent.com/4480601/49070073-bd16d480-f222-11e8-945f-0af6552d88fd.gif)

**Comment by nyalldawson** [comment]
@jonnyforestgis it's not directly related here, but you should upgrade to 3.4.2 -- it fixes many issues

**Comment by jonnyforestGIS** [comment]
Ups ok  :+1:  Sorry for the noise.
