### ISSUE TITLE
Layer paths Windows 64

### ISSUE THREAD

**Issue by rxlacroix** [north-road/qgis-processing-r#21]
Fantastic job! This really widens the field of possibilities!

I encountered a classic R issue with layer paths on Windows (10-64bits) : they contain `\`

`Error: '\U' used without hex digits in character string starting "'C:\U"
Execution halted
`

In the meantime, a little trick to dodge that is to drag the layers into QGIS rather than adding them by the traditional method (Layer > Add Layer...). In this way, the layer paths will have `/` and so you can use them.

**Comment by barryrowlingson** [comment]
Referenced in a few SO questions, eg:

https://gis.stackexchange.com/questions/309975/processing-r-provider-plugin-for-qgis-3-4?noredirect=1#comment502404_309975
