### ISSUE TITLE
create new .rsx file

### ISSUE THREAD

**Issue by wguthe** [north-road/qgis-processing-r#27]
I'm finding the same buggy editor problem noted in November.  The Create New R Script button in the Processing Toolbox forces my rsx script to have a .py extension.  Can it be set to store it as an .rsx file in the appropriate rscripts directory?
Also, earlier versions of this plug-in were aware of selections in vector datasets, and would process only the selected records.  The current version doesn't seem to do this.  It'd be great if that function was back.

**Comment by nyalldawson** [comment]
Can you test with a new QGIS profile? I suspect you have outdated components from an earlier plugin version causing issues here.

**Comment by wguthe** [comment]
Hi, Nyall.  Thanks, the plug-in now works correctly in QGIS 3.4.5 on Windows 10.  It runs on all the features in a dataset, rather than only on selected features/records, however.  Will that capability be added later?

Best,
Bill

**Comment by nyalldawson** [comment]
@wguthe  - yes, see #28
