### ISSUE TITLE
Using system folder still cause a lot of package downloading

### ISSUE THREAD

**Issue by ghtmtt** [north-road/qgis-processing-r#3]
With the `Use user library folder instead of system libraries` unchecked still cause a lot of package downloading. 

The default R installation has 32 packages while the QGIS rlib has 114 libraries.

When using system libs QGIS R provider still downloads all the remaining libraries

**Comment by nyalldawson** [comment]
I'm not sure what the issue here is -- if those libraries haven't been installed system wide, then QGIS will still need to install them somehow. Maybe I'm misinterpreting?

**Comment by ghtmtt** [comment]
Yep, the question is: are **all** the 114 libraries needed to work with R in QGIS? With the old provider (same computer) the 32 libraries were enough.

**Comment by nyalldawson** [comment]
@ghtmtt can we close this? I don't think there's anything actionable here.

**Comment by ghtmtt** [comment]
+1 thanks!
