### ISSUE TITLE
multiple field layer selection no longer works

### ISSUE THREAD

**Issue by Florent-Demoraes** [north-road/qgis-processing-r#32]
Hi, thanks a lot for this QGIS R processing provider

In the QGIS 2.18 the following syntax worked fine :
##Active_variables_Must_be_numeric=multiple Field Layer

It allowed to select fields from a layer by picking them in a left list through a GUI.
The selected fields used to appear in a right list.

This function no longer works.

The full script is available here : 
https://github.com/ESO-Rennes/FactoQGIS/blob/master/Typological_Analysis_PCA_and_HAC.rsx

Thanks for your help.

**Comment by nyalldawson** [comment]
This is actually an issue in the script, and how the inputs are defined.

E.g. the line should be

    ##Active_variables_Must_be_numeric=Field multiple Layer

(or better - this forces the numeric constraint)

   ##Active_variables_Must_be_numeric=Field numeric multiple Layer

A fixed list of definitions is:

```
##FactoQGIS=group
##Language=selection English
##Working_directory_Mandatory=Folder
##Layer=Vector
##Row_name=Field Layer
##Active_variables_Must_be_numeric=Field numeric multiple Layer
##Scale_data=selection TRUE;FALSE
##Number_of_axes_to_be_kept_for_PCA=Number 5
##Number_of_axes_to_be_kept_for_HAC=Number 2
##Number_of_clusters_to_be_kept_for_HAC=Number 5
##Metric_to_be_used_to_build_the_tree=selection euclidean;manhattan
##Aggregation_method_to_be_used_to_define_clusters=selection ward;average;single;complete
##Eigen_Value_Table=output table
##Variable_Coordinates_Table=output table
##Layer_with_Clusters=vector output
```
