### ISSUE TITLE
plugin version 1.0.6 do not works

### ISSUE THREAD

**Issue by FSantosCodes** [north-road/qgis-processing-r#34]
hello,

I am trying to use the processing R  provider but version 1.0.6 seems to not recognize any input according to its reference: 

https://docs.qgis.org/2.14/en/docs/training_manual/processing/r_syntax.html

if the project is not continued, can you please inform it to avoid losing time with its bugs? otherwise check these: the plugin do not recognize any variable (v 1.0.6), it is not possible to declare a selection (in any version), documentation is not enough informative (e.g. how can I declare a vector of strings such as: c("a","b","c")?.

Thanks for your support.

**Comment by nyalldawson** [comment]
This plugin does work, and is maintained. It's just that you're looking at docs for qgis 2.14.

**Comment by quinaia** [comment]
I have the same problem, and even following the latest documentation, I can't use the plugin.

https://docs.qgis.org/3.4/pt_BR/docs/training_manual/processing/r_syntax.html?highlight=script

**Comment by nyalldawson** [comment]
Fixed in version 1.0.7
