### ISSUE TITLE
QGIS 3.4 does not recognize Processing R provider 1.0.6 syntax

### ISSUE THREAD

**Issue by quinaia** [north-road/qgis-processing-r#35]
I am not a developer, I am a user of the plugin “Processing R provider”, but from July 30 this year, I can not use anymore. I currently use windows 10 and windows 8, QGIS 3.4.6 and R 3.6, on both operating systems when I try to load a layer (shapes, raster, tables and etc) an error appears "This algorithm cannot be executed :frowning:
This script has a syntax error. Problem with line: ## Y = Field Layer "
I already searched among users and they also can’t use the plugin in QGIS version 3.4.6. I hope I can count on your help. Thanks for listening.

**Comment by nyalldawson** [comment]
Please check that there's no spaces in the definition line.

**Comment by quinaia** [comment]
I just tried ... same syntax error. Unfortunately.

**Comment by nyalldawson** [comment]
Can you share your entire script please?

**Comment by quinaia** [comment]
actually the script that came in the plugin root doesn't recognize the so-called "scatterplot"

**Comment by nyalldawson** [comment]
Can you share the script you are using?

**Comment by quinaia** [comment]
##Analysis=group
##showplots
##Layer=vector
##Field=Field Layer
hist(Layer[[Field]], main=paste(“Histogram of”,Field), xlab=paste(Field))

**Comment by nyalldawson** [comment]
Ok - that one works fine for me. 

>  QGIS version 3.4.6

Can you please upgrade to 3.4.10 and re-test?

**Comment by quinaia** [comment]
the version i'm using is 3.4.10

In addition, I have already reinstalled trying to correct this problem and still persists.
maybe something got corrupted in qgis python ... but not sure.

did you test with win 10?

when I tested on another computer with win 8 gave the same syntax problem, I may have to format the computers.

**Comment by nyalldawson** [comment]
Ok - got it! fix incoming

**Comment by nyalldawson** [comment]
Fixed in version 1.0.7 -- will hit the plugin repos within the next hour

**Comment by quinaia** [comment]
Great Job! All working here!!
