### ISSUE TITLE
Graphic output does not showing up in QGIS 3.8

### ISSUE THREAD

**Issue by dquang** [north-road/qgis-processing-r#36]
Hi,

thank you very much for the great job with this plugin. It helps a lot. I am just wondering if something wrong either with Windows 10 64bit or QGIS 3.8 that the Plot Output is simply a blank page. I tried with my script and also the example script delivered with the plugin, both had the same problem. Console output works normal.

By the way, I saw that there was a closed issue with path problem. I still have this problem, that the path to File (variable input) is not converted from "\" to "/" and R cannot work with that. My solution is simply converting them by using R command.

Regards,
Quang

**Comment by nyalldawson** [comment]
Are you able to share scripts and logs from executing them?

**Comment by dquang** [comment]
Here is my script, just make a simple one:
```
##showplots
data(mtcars)
outPlot <- plot(mtcars$mpg, mtcars$cyl)
>outPlot
```

Log Output: - Plot Output is blank
```
QGIS version: 3.8.2-Zanzibar
QGIS code revision: 4470baa1a3
Qt version: 5.11.2
GDAL version: 2.4.1
GEOS version: 3.7.2-CAPI-1.11.0 b55d2125
PROJ version: Rel. 5.2.0, September 15th, 2018
Processing algorithm…
Algorithm 'test' starting…
Input parameters:
{ 'RPLOTS' : 'TEMPORARY_OUTPUT', 'R_CONSOLE_OUTPUT' : 'TEMPORARY_OUTPUT' }

R execution commands
options("repos"="http://cran.at.r-project.org/")
tryCatch(find.package("rgdal"), error=function(e) install.packages("rgdal", dependencies=TRUE))
tryCatch(find.package("raster"), error=function(e) install.packages("raster", dependencies=TRUE))
library("raster")
library("rgdal")
png("D:/Users/XXX/AppData/Local/Temp/processing_a16a6c3f15744f36a1f8e5aa765eaa48/5276517e78d54c829117fcd8d7424549/RPLOTS.png")
data(mtcars)
outPlot <- plot(mtcars$mpg, mtcars$cyl)
outPlot
dev.off()
R execution console output
[1] "D:/R/R360/library/rgdal"
[1] "D:/R/R360/library/raster"
Lade nötiges Paket: sp
Warnmeldung:
Paket 'raster' wurde unter R Version 3.6.1 erstellt
rgdal: version: 1.4-4, (SVN revision 833)
Geospatial Data Abstraction Library extensions to R successfully loaded
Loaded GDAL runtime: GDAL 2.2.3, released 2017/11/20
Path to GDAL shared files: D:/R/R360/library/rgdal/gdal
GDAL binary built with GEOS: TRUE
Loaded PROJ.4 runtime: Rel. 4.9.3, 15 August 2016, [PJ_VERSION: 493]
Path to PROJ.4 shared files: D:/R/R360/library/rgdal/proj
Linking to sp version: 1.3-1
NULL
null device
1
Execution completed in 1.67 seconds
Results:
{'RPLOTS': 'D:/Users/XXX/AppData/Local/Temp/processing_a16a6c3f15744f36a1f8e5aa765eaa48/88dcc9d0759e411882d380d5b6dd591d/RPLOTS.html',
'R_CONSOLE_OUTPUT': 'D:/Users/XXX/AppData/Local/Temp/processing_a16a6c3f15744f36a1f8e5aa765eaa48/4b0580d3cbee406fb95fe3482b562fd1/R_CONSOLE_OUTPUT.html'}

Loading resulting layers
Algorithm 'test' finished
HTML output has been generated by this algorithm.
Open the results dialog to check it.
```

If there was an input File e.x `##inFile=File c:\dir\file.txt ` it will cause error in R because of the escape character. This happens also when the file was chosen by a dialogue.

**Comment by dquang** [comment]
After digging in the code, I found that if I change `line 309` in file `processing_r\processing\algorithm.py` to `f.write('<html><img src="file:///' + self.plots_filename + '"/></html>')` (adding `file:///`) it will show plots correctly.

For correcting the path strings that are passed from QGIS, I changed `line 415` to `file_path = source_parts.get('path').replace('\\', '/')`

I am using Windows 10 64 bit and FireFox. I don't know if these changes would help for other Browsers/OSes.

Thank again for the great job you did.

**Comment by nyalldawson** [comment]
Can you test if the latest commits fix the issue for you?

**Comment by dquang** [comment]
@nyalldawson, yes, however still a small problem.

The problem with displaying plots was cleared with the new commit. The input path works with `Vector/Raster` types but `File`.  I would suggest updating the `build_import_commands`, separating `QgsProcessingParameterFile `like this:

```
elif isinstance(param, QgsProcessingParameterFile):
    value = self.parameterAsString(parameters, param.name(), context)
    commands.append('{}="{}"'.format(param.name(), QDir.fromNativeSeparators(value)))
```

**Comment by nyalldawson** [comment]
Thanks! Can you test master now? If all looks good I'll package up and push out a new version.

(Your testing & fixes are very much appreciated!)

**Comment by dquang** [comment]
Thank you very much for the new commit. I confirm that it works also when users choose not to use `raster/rgdal` .
