### ISSUE TITLE
Processing R - Ubuntu linux

### ISSUE THREAD

**Issue by pierluigiderosa** [north-road/qgis-processing-r#38]
Running processing R under linux I found this error:

`TypeError
__init__() got an unexpected keyword argument 'encoding'`

Under **check_r_installed**()
Line 315

for the **_utils.py_**
Did you tested che plugin under linux?
Thanks

**Comment by nyalldawson** [comment]
Likely you are using an unsupported older python version - can you confirm your version?

**Comment by pierluigiderosa** [comment]
I'm using ubuntu 16.04 -- QGIS 3.4

Under python console I have:

```
print(sys.version)
3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]
```

Is it fine?

**Comment by nyalldawson** [comment]
Thanks for the confirmation -- I'll add a workaround for this
