### ISSUE TITLE
No activation option in Qgis

### ISSUE THREAD

**Issue by neigun** [north-road/qgis-processing-r#39]
Sorry there does not appear to be away of changing the title of the post.

Running Qgis 3.8.2 on Ubuntu 19.04
Version installed 1.0.7

Despite R being installed and the Spatstat package, the plug in does not recognise the appropriate folder.   

R Folder /usr/bin  gives scatterplot though.

What would be the path for the R scripts on a Linux system?

**Comment by nyalldawson** [comment]
Do you see the entries in the toolbox? There is no activate option for this plugin (since it's activated by the plugin being enabled)

**Comment by neigun** [comment]
Sorry I found out after I posted the query that there is no activation option.  

The options to select the paths are there, I just don't know which folders to link them to in Ubuntu/Linux.  The only examples I could find relate to Windows.

**Comment by nyalldawson** [comment]
You should be able to leave them blank on linux, as long as r has been installed to your system path. Try running Rscript from a terminal window and check that it's present.

**Comment by neigun** [comment]
I think the problem might relate to permissions.

Rscript was installed:

neil@neil-desktop:~$ Rscript
Usage: /path/to/Rscript [--options] [-e expr [-e expr2 ...] | file] [args]

--options accepted are
  --help              Print usage and exit
  --version           Print version and exit
  --verbose           Print information on progress
  --default-packages=list
                      Where 'list' is a comma-separated set
                        of package names, or 'NULL'
or options to R, in addition to --slave --no-restore, such as
  --save              Do save workspace at the end of the session
  --no-environ        Don't read the site and user environment files
  --no-site-file      Don't read the site-wide Rprofile
  --no-init-file      Don't read the user R profile
  --restore           Do restore previously saved objects at startup
  --vanilla           Combine --no-save, --no-restore, --no-site-file
                        --no-init-file and --no-environ

'file' may contain spaces but not shell metacharacters
Expressions (one or more '-e <expr>') may be used *instead* of 'file'
See also  ?Rscript  from within R


I'm also getting a Python error in Qgis:
2019-09-17T18:36:39     WARNING    Traceback (most recent call last):
              File "/usr/share/qgis/python/plugins/processing/gui/ProcessingToolbox.py", line 238, in executeAlgorithm ok, message = alg.canExecute()
              File "/home/neil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/algorithm.py", line 279, in canExecute msg = RUtils.check_r_is_installed()
              File "/home/neil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/utils.py", line 315, in check_r_is_installed
              universal_newlines=True) as proc:
              File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
              restore_signals, start_new_session)
              File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
              raise child_exception_type(errno_num, err_msg, err_filename)
             PermissionError: [Errno 13] Permission denied: '/usr/lib/R'

**Comment by nyalldawson** [comment]
I can't explain that one... Does "R --version" work from the command line?

**Comment by neigun** [comment]
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

**Comment by nyalldawson** [comment]
OK, you've successfully confused me! 😱 

If you try making a tiny standalone python script which just runs the R version command, just like https://github.com/north-road/qgis-processing-r/blob/master/processing_r/processing/utils.py#L309 , does it work?

**Comment by neigun** [comment]
I labelled the script test.py

neil@neil-desktop:~$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    from processing.core.ProcessingConfig import ProcessingConfig
ModuleNotFoundError: No module named 'processing'

**Comment by nyalldawson** [comment]
I think you misunderstood - I mean a minimal script which only calls subprocess and executes R --version.

**Comment by neigun** [comment]
Sorry, I've not run Python scripts before.
What part do you want me to run?

**Comment by nirvn** [comment]
@neigun , by default, the processing R provider only has one test script called Scatterplot. If you see that in your panel, congratulations, the provider is running :) 

To create new R-based script use the processing panel's toolbar:
![image](https://user-images.githubusercontent.com/1728657/65210041-0858e700-dac4-11e9-88e0-75d0580b4841.png)

**Comment by neigun** [comment]
I did have scatterplot working at one point, but somewhere a long the line........

If I try running an R script in the new R script dialogue box Qgis chucks out the same error message I quoted above. From reading around it appears to be an issue with permissions.  Later I am going to give this a shot:
https://stackoverflow.com/questions/46815585/linux-server-python-oserror-errno-13-permission-denied

**Comment by nyalldawson** [comment]
It's highly likely this is a local issue, as I've had others test under the same environment without issue.

How did you setup r? Python? Qgis? Using wanting abnormal like snaps here?

**Comment by neigun** [comment]
I've done an upgrade to Ubuntu 19.10, and re-installed Qgis and R using cli. No snaps.
This is the error message I get when I try to run Scatterplot in Qgis:
2019-09-23T16:36:28     WARNING    Traceback (most recent call last):
              File "/usr/share/qgis/python/plugins/processing/gui/ProcessingToolbox.py", line 239, in executeAlgorithm
              ok, message = alg.canExecute()
              File "/home/neil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/algorithm.py", line 279, in canExecute
              msg = RUtils.check_r_is_installed()
              File "/home/neil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/utils.py", line 315, in check_r_is_installed
              universal_newlines=True) as proc:
              File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
              restore_signals, start_new_session)
              File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
              raise child_exception_type(errno_num, err_msg, err_filename)
             PermissionError: [Errno 13] Permission denied: '/usr/lib/R'

From some searching around it sounds like a permissions issue.  R seems to run OK from cli.

**Comment by neigun** [comment]
I've done an upgrade to Ubuntu 19.10, and re-installed Qgis and R using cli. No snaps.
This is the error message I get when I try to run Scatterplot in Qgis:
2019-09-23T16:36:28     WARNING    Traceback (most recent call last):
              File "/usr/share/qgis/python/plugins/processing/gui/ProcessingToolbox.py", line 239, in executeAlgorithm
              ok, message = alg.canExecute()
              File "/home/neil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/algorithm.py", line 279, in canExecute
              msg = RUtils.check_r_is_installed()
              File "/home/neil/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/utils.py", line 315, in check_r_is_installed
              universal_newlines=True) as proc:
              File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
              restore_signals, start_new_session)
              File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
              raise child_exception_type(errno_num, err_msg, err_filename)
             PermissionError: [Errno 13] Permission denied: '/usr/lib/R'

From some searching around it sounds like a permissions issue.  R seems to run OK from cli.

**Comment by nyalldawson** [comment]
There's still something else at play here -- I've confirmed with other users of Ubuntu and there's no issue. 

Is there some other security options you've manually enabled somewhere on your system?

**Comment by neigun** [comment]
I cleared the option to direct Qgis to the R folder and let it go to default and it worked.

Thanks for your help.
