### ISSUE TITLE
Include documentation in plugin repository

### ISSUE THREAD

**Issue by JanCaha** [north-road/qgis-processing-r#44]
As mentioned here [https://github.com/north-road/qgis-processing-r/issues/41](https://github.com/north-road/qgis-processing-r/issues/41). The documentation should move from QGIS manul to its own pages.

My suggestion is to take the existing documentation, turn it into [mkdocs](https://www.mkdocs.org/) website and manage the deployment to github pages through travis.

Does it seem like a reasonable idea?

**Comment by nyalldawson** [comment]
Yes, sounds perfect! Are you volunteering to do this? I'm happy to update the deciding qgis docs to reflect the current plugin version, but don't have time at the moment to setup the initial infrastructure...

**Comment by JanCaha** [comment]
Yes. I did some initial testing yesterday and it seems to be working just fine. I will build the website as a separate project for now, then merge it to my fork and then we can merge it with the main branch. 

I will keep you posted in this thread about it.

**Comment by nyalldawson** [comment]
Sounds fantastic -- loving your work here!! 😁

**Comment by JanCaha** [comment]
I am glad to that I can help. I am long time fan of your work and North Road :)

I am using R a lot and quite often with QGIS so this seems like something worth dedicating my time to.

Btw: It seems to be working, repo [here](https://github.com/JanCaha/qgis-processing-r-website) and the [website](https://jancaha.github.io/qgis-processing-r-website/).

I guess that there is a lot of stuff to fix. I found some sources in QGIS documentation, but I am not sure that I got all of it. Feel free to open issues in the repo for anything that can/should be fixed.

**Comment by JanCaha** [comment]
After the 2.0.0 release, it might be a good idea to get back to this topic. I have the set up working in my fork with the final website available here: [https://jancaha.github.io/qgis-processing-r/](https://jancaha.github.io/qgis-processing-r/).

Unfortunately, the setup will require more than simple branch merge. There are a few settings that need to be done by hand. But besides that, it seems to work just fine.

**Comment by nyalldawson** [comment]
This is brilliant - I love it!

I'd be happy to get you rights to this repo if that would help with the setup?

**Comment by JanCaha** [comment]
The setup follows step by step [this tutorial](https://derekweitzel.com/2017/02/08/deploying-docs-on-github-with-travisci/).
Upon accepting PR you would need to generate encrypted key, insert public key into repo settings and replace one line in travis setup. 

Or I can set it up here if you grant me the rights. Both versions work just fine for me. It's up to you :-)

**Comment by nyalldawson** [comment]
Well, I'd love to expand the team working on this provider, and you've obviously got the coding skills and R knowledge required! I'd love to have you onboard officially if you're keen on becoming a maintainer.

**Comment by JanCaha** [comment]
I would love to. I really like this chance to merge QGIS with R.

**Comment by nyalldawson** [comment]
Welcome aboard @JanCaha !
