### ISSUE TITLE
Missing "Get R scripts from on-line scripts collection"

### ISSUE THREAD

**Issue by havatv** [north-road/qgis-processing-r#49]
This is an extremely useful plugin!
I am trying to update the QGIS documentation on the use of R with QGIS 3. I and can't find ``R-> Tools`` or its entry ``Get R scripts from on-line scripts collection`` the processing toolbox (they were available when using R in QGIS 2).
Am I missing something? Will this useful feature be implemented? Are there any workarounds?
Are the scripts available somewhere?

**Comment by nyalldawson** [comment]
It's not implemented in the plugin. The original intention for QGIS 3. was that the "resource sharing" plugin would take over this particular role -- but I'm not sure what the status with that plugin is or how well it is being maintained.

**Comment by havatv** [comment]
Thanks for the information, @nyalldawson!
I have tried to install the "resource sharing" plugin, but it seems to only contain icon / symbology / style related repositories.
I found the QGIS rscripts collection on https://github.com/qgis/QGIS-Processing/tree/master/rscripts (archived repository), so we can point to that for the time being.

**Comment by havatv** [comment]
Sorry to bother you, but I had one more question, and that was about the `Tools`` menu under R in the processing toolbox.
According to the QGIS documentation there used to be a "Create new R script" tool there (I think I remember it from QGIS 2).
Are there any plans to reintroduce this tool in the Processing Toolbox? I think it would be very useful for our users.
If it will not be reintroduced, I will update the documentation accordingly.

**Comment by nyalldawson** [comment]
You should see that in the toolbar above the processing algorithms list. Note that there's any upstream qgis issue which means you need to restart to see this after first installing the plugin...

**Comment by havatv** [comment]
Thanks, @nyalldawson.  I see it now.  Sorry about the noise.
I will update the documentation.

**Comment by havatv** [comment]
PR https://github.com/akbargumbira/qgis_resources_sharing/pull/62 adds R script support to the *QGIS Resource Sharing* plugin, and the QGIS 2 online R script collection has been added to the *QGIS Resources Sharing Repository* (https://github.com/qgis/QGIS-Resources/tree/master/collections/qgis_rscripts).
Adding some R scripts should therefore be reasonably convenient in the future.
When the *QGIS Resource Sharing* plugin PR is merged and a new version of the plugin is published, I will update the QGIS documentation.

**Comment by havatv** [comment]
There are360 R scripts (some sf and some sf and some sp) vailables i a clollectiion in the QGIS official repository.
.After installation they will show up in the processing toolbox, under ***R***..The "scripts from the odl" scripts collection are avlailable in a sepsrate collection.
This is expliuned /described in the 3rd psrty chapter of the user manual.l.And the plugin is maintained,New version is coming soon
 

 

Mvh

Styret
