### ISSUE TITLE
Missing functionality to add Algorithm Help

### ISSUE THREAD

**Issue by ghtmtt** [north-road/qgis-processing-r#5]
In the old provider there was a button in the editor where the user could add the guide of the algorithm.

**Comment by ghtmtt** [comment]
Thanks for the fix. But As far as I understand, the user has to add manually the ``alg.rsx.help`` file and write a `json` file. Is this correct? If yes, do you think it is possible to add a button in the editor (or another simpler solution) where the user can write e text like file rather than a `json` one?

**Comment by nyalldawson** [comment]
@ghtmtt 

yes that's correct -- the script editor needs considerable work here to make it usable for the r provider. That's still a WIP.

**Comment by ghtmtt** [comment]
ok perfect good to know. As usual consider me as tester :) thanks!
