### ISSUE TITLE
[Feature idea] Input with predefined set of values

### ISSUE THREAD

**Issue by JanCaha** [north-road/qgis-processing-r#55]
I think that it would be useful to allow inputs that only take values from a specified set of values.

I am thinking about a definition like:
`##variable=[a,b,c,d]`
Which should create GUI of SelectBox with four options.

This could be highly beneficial for R functions with various computation algorithms (i.e. correlation have several possible methods ("pearson", "kendall", "spearman")). This could make R scripts more general through the possibility to expose these options to user instead of hardcoding them in the rsx script.

I see that it is likely to be done using QgsProcessingParameterEnum, but I am wondering if there are some examples to look at. Any tips @nyalldawson ?

**Comment by JanCaha** [comment]
Oh, it is actually implemented in the plugin! My bad. As I started to look through the code, how this could be handled I found the implementation of Enum. It is just not documented anywhere, which need to be fixed, as it is super useful.

**Comment by JanCaha** [comment]
Looking at how the  QgsProcessingParameterEnum works, it seems that it is possible to obtain just order of selected item from SelectBox (as a number) but not the actual string representing the item. 

For example, if I create Enum like this:
##test=selection a;b;c;d
The variable test will have a value between 0 and 3, but it is not possible to extract strings "a" to "d". 

That is not very convenient for the R scripts, as the example above shows.

I can imagine one dirty hack, how to do handle it in the process of creating R script while parsing the **rsx** file. But I would like to be sure that I am not missing something about QGIS API first.

**Comment by JanCaha** [comment]
The branch [https://github.com/JanCaha/qgis-processing-r/tree/enum_tests](https://github.com/JanCaha/qgis-processing-r/tree/enum_tests) shows testing implementation of extracting enum values as string.

Example script working with that solution is:
`
##Test enum=name
##Layer=vector
##X=Field Layer
##Y=Field Layer
##cor_type=enum pearson;kendall;spearman

>print(cor_type)
>cor(x = Layer[[X]], y = Layer[[Y]], method = cor_type)
`

**Comment by nyalldawson** [comment]
I don't think we can change the current behavior without breaking existing scripts. What we could do here though is create an alias for the "enum" type which indicates that the string literal is desired instead of the numeric index. E.g.

```
##cor_type=enum_literal pearson;kendall;spearman
```

Alternatively we could just write this off as an upstream limitation and address it inside QGIS itself, by adding an option for a "literal" flag on enum parameters. There's been feature requests filed upstream asking for this too, so I think it **should** be done upstream.

I guess if you want something pre QGIS 3.12, we could add our own literal keyword here:

    ##cor_type=enum literal pearson;kendall;spearman

and for < 3.12 we do some wrangling in the R provider to handle this, and for >= 3.12 rely on inbuilt support in QGIS?

**Comment by JanCaha** [comment]
Ok, this seems to make sense. It is great that it's been considered in QGIS upstream. It should be quite useful.

It seems reasonable to handle it by a literal keyword for now and use the inbuilt support when it's available.

I will take a look if I can figure out how to handle the proposed version using the literal keyword. I would like to go with the version:
```
##cor_type=enum literal pearson;kendall;spearman
```

**Comment by JanCaha** [comment]
@nyalldawson Could you please take a look at the solution in [this branch](https://github.com/JanCaha/qgis-processing-r/tree/enum_tests)? It passes all the tests and works only if `enum literal` is defined, otherwise it acts normally. So it should not break existing scripts. It should also be reasonably simple to add exceptions for versions once the feature is implemented in the QGIS upstream.

**Comment by nyalldawson** [comment]
It looks on the right track to me, but we'll need to ensure that any existing scripts with the old behavior don't break -- to me it looks like this will break non-literal enum parameters?

**Comment by JanCaha** [comment]
While writing a test to prove that this does not break existing scripts, I found a way to make it much more straightforward. 

The current version even includes test that shows that it is possible to have both types of enums side by side.

**Comment by nyalldawson** [comment]
Hi @JanCaha  - this is still on my mind, I've just been smashed with tasks this week -- I hope to review early next week, but please keep hassling me about it :laughing:

**Comment by JanCaha** [comment]
Hi @nyalldawson no problem. I understand that should be reviewed in detail as there is a potential to mess things up. Feel free to take your time ;-)

**Comment by JanCaha** [comment]
Just bumping this ;-)

**Comment by JanCaha** [comment]
Any chance of sorting this out? :)
