### ISSUE TITLE
Build website using GitHub Actions instead Travis

### ISSUE THREAD

**Issue by JanCaha** [north-road/qgis-processing-r#57]
I just realised that building and deploying of the doc website using Travis is probably a little bit problematic. Since pull requests cannot deploy into the main repo, their Travis build automatically fails, which is problematic since it requires manual check of Travis to figure out the reason for the failure (likely website deploy issue). 

I recently tested Github Actions which allow all sorts of automatic tasks to be performed including doc release. It is also much faster than Travis build as it will perform just website build and deployment and it can be also configured so, that it will only take commits that affect specific repository.

I see it as a reasonable alternative. I have tested it and looks quite ok. If there are no objections I will do the move tomorrow.

**Comment by nyalldawson** [comment]
Sounds great to me!

**Comment by JanCaha** [comment]
It is all working now.

I am sorry I didn't realize that multi-purpose travis builds do not work very well for pull requests.  I guess you have to learn it the hard way.
