### ISSUE TITLE
Error handling when R script error occurs

### ISSUE THREAD

**Issue by cratcliff** [north-road/qgis-processing-r#71]
I have been using the _[Example with file/table output](https://north-road.github.io/qgis-processing-r/ex_file_output/)_ as a starting point to learn how to implementing my own R script. 

My R provider setup is as follows: (R is not installed in Program Files due to administration rights), and I am using QGIS R Provider version 2.2.1.
![image](https://user-images.githubusercontent.com/29470818/88351454-8c8b9300-cd95-11ea-8ebb-da0316d0ec5e.png)

In QGIS LTR 3.10.3 when running the _Example with file/table output_ script copied directly from the webpage I get 
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxx\\AppData\\Local\\Temp/processing_08962aa0287b4dd18d1d2228ea8cc510/6df35e991d7a4a8ab13ec4115308e5e9/processing_values.txt'` error (log file: [QGIS_LTR_3.10.3_Rplugin.log](https://github.com/north-road/qgis-processing-r/files/4969859/QGIS_LTR_3.10.3_Rplugin.log) ).
I think this is triggered when an error occurs within the R script. In this case the error is `Error: '\U' used without hex digits in character string starting ""C:\U"`. 

I have also tried this in QGIS 3.12.3 in which for some reason the _hex digits_ error does not occur,  so I forced an R script error by changing the last line to     `Stat <- Stat_fil` and got the same error (see log: [QGIS_3.12.3_Rplugin.log](https://github.com/north-road/qgis-processing-r/files/4969893/QGIS_3.12.3_Rplugin.log)
 )

Is this the expected behaviour from the Processing R plugin when an error within the R script is encountered?

**Comment by nyalldawson** [comment]
3.10.3 is quite old now -- is it possible to test on a more recent 3.10 release? There's been a lot of fixes in 3.10 relating to processing and it's likely this was fixed in qgis itself.

**Comment by nyalldawson** [comment]
Closing due to lack of feedback
