### ISSUE TITLE
Conflict between sf and sp packages

### ISSUE THREAD

**Issue by SSGoveia** [north-road/qgis-processing-r#78]
I'm having trouble using gstat in QGIS because Processing R Provider ignores the functions of the sp package because it uses sf by default
Even calling sp Processing interprets the functions as sf resulting in an error

**Comment by JanCaha** [comment]
You have to specify: `##load_vector_using_rgdal` in the header of the script. Then the data is loaded using packages `rgdal` and `sp`, without loading `sf`. 

If that does not work, you would need to share the script for further study.

**Comment by SSGoveia** [comment]
Thank you! It worked!
