### ISSUE TITLE
Help file reading issue (possibly upstream problem)

### ISSUE THREAD

**Issue by JanCaha** [north-road/qgis-processing-r#82]
Current problem causing tests to fail i.e. [here](https://github.com/north-road/qgis-processing-r/runs/1848657741) caused by this [test line](https://github.com/north-road/qgis-processing-r/runs/1848657741) seems to be an upstream issue. (Or it could be misunderstang of what should really happen.)

The problem, the way I undrestand, it is that if you load `help` file for algorithm it does not associate the help text with individual paramaters of the algorithm.

The help string works fine for whole algorithm but not for specific parameter.

It is probably not necessary to even test this, it would be quite ok to remove this part of test. But it seems to be worth knowing about as it might be upstream problem.

**Comment by nyalldawson** [comment]
It needs a patch which is in QGIS 3.16.4 or later (which is unreleased yet). We could conditionally skip this particular test on earlier versions...

**Comment by JanCaha** [comment]
Ok, should be fixed using #83.

Interesting is that it still fails with dev version (3.17.0-Master) .
