### ISSUE TITLE
Manually add R folder

### ISSUE THREAD

**Issue by simbamangu** [north-road/qgis-processing-r#9]
On Mac OSX, was necessary to identify the R folder manually in Processing options, perhaps this should be a default?

`/usr/local/bin`

**Comment by nyalldawson** [comment]
How was R installed?

**Comment by ghtmtt** [comment]
@simbamangu I'm definitely not an OSX expert but what if in a terminal you type ``which R``? This should output the R path

**Comment by simbamangu** [comment]
> How was R installed?

Homebrew - `brew cask install r-app` (actually may have been a dependency installed with `brew cask install rstudio`). 

This gives an R.app in /Applications and also executables in /usr/local/bin, both of which are symlinked to `/Library/Frameworks/R.framework/Resources/bin/R`.
